### ISSUE TITLE
meet the message "module is not defined" using is-loading with jquery.

### ISSUE THREAD

**Issue by angkk2u** [hekigan/is-loading#18] opened 2017-04-19 02:30 UTC
I've been using it since version 1.
I want to use the updated version, but the message " Module is not defined " is displayed.

I imported isLoading.js from npm, is it wrong?

**Browser Version: Chrome
Node.js Version: not Node.js, jquery 1.12.4

**Comment by hekigan** [comment] 2017-04-19 03:21
You are right, I am going to look that up tonight and fix it as soon as possible.
Thank you for the feedback

**Comment by hekigan** [comment] 2017-04-19 16:24
Ok, this is fixed with the release 2.0.3. It's also pushed on npm, so you can just install it like usual.
I tested it with the code below and it was working. If you have another problem, don't hesitate to report it.

```html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="node_modules/is-loading/css/index.min.css">
</head>
<body>

    <div class="demo well">
        <p class="alert">container</p>
        <span class="btn">test</span>
    </div>

    <script type="text/javascript" src="./node_modules/is-loading/dist/isLoading.min.js"></script>
    <script type="text/javascript">
        var button = document.querySelector('.btn');

        button.addEventListener('click', function(e) {
            // start the loading script
            isLoading(e.target).loading(); // or isLoading(button).loading()

            setTimeout(function() {
                // stop the loading script
                isLoading(e.target).remove(); // or isLoading(button).remove()
            }, 1000 );
        });
    </script>

</body>
</html>
```

**Closed** 2017-04-20 15:11 UTC
Labels: bug

**Comment by angkk2u** [comment] 2017-04-21 08:01
Thank you for your prompt response.

".is-loading-element-overlay" does not disappear when "remove ()" is called.

So I am adding the following code.


```
From IsLoading.prototype.remove
if(this._target){
    this._target.removeAttribute('data-is-loading-content');
    //new line below
    document.querySelector('.is-loading-element-overlay').remove();
}
```

**Comment by hekigan** [comment] 2017-04-21 12:05
I will also double check that

**Comment by hekigan** [comment] 2017-04-21 18:04
I could not reproduce your bug.
When you go to the example page:
http://hekigan.github.io/is-loading/

Do you also get the same problem that you were describing?
If yes, then do you get an error in the console?
Your browser is Chrome, but what version and on which platform?

**Comment by angkk2u** [comment] 2017-04-25 07:48
Can you check this code?

There is no console error, but the behavior after "remove ()" is strange.

Browser : Chrome 57.0.2987.133 & Safari (Mac)


<img width="338" alt="click" src="https://cloud.githubusercontent.com/assets/12946287/25373918/6cf951c8-29d6-11e7-8d9c-0cdcc7a804e5.png">

<img width="496" alt="after remove" src="https://cloud.githubusercontent.com/assets/12946287/25373926/748044ce-29d6-11e7-9ecf-d9824823c971.png">



```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" type="text/css" href="./css/index.css">

    <style>
        .demo{
            height:300px;
            width:300px;
            border:1px solid #000000;
        }
    </style>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="./dist/isLoading.js"></script>

    <script>
        $(document).ready(function(){
            $(".btn").click(function(){
                console.log("test");
                var load = isLoading($(".demo")[0], { type: 'overlay' });
                load.loading();

                setTimeout(function() {
                    // Deactivate the loading script
                    load.remove();
                }, 2500 );
            });
        });

    </script>
</head>
<body>
<div class="demo well">
    <p class="alert">container</p>

</div>
<input type="button" class="btn" value="test">
</body>
</html>

```

**Comment by angkk2u** [comment] 2017-04-25 09:58
from IE

SCRIPT438: Object doesn't support property or method



![image](https://cloud.githubusercontent.com/assets/12946287/25379762/08086926-29e9-11e7-9b6f-bf3f29b4c088.png)

**Comment by hekigan** [comment] 2017-05-02 03:37
Hi, just to drop a quick message.
I did not forget about the current issue, but I am fairly busy at the moment so I can't take a look right away.
I will do so as soon as I am available.
And thank you for the detailed explanation, that is very helpful!

**Comment by angkk2u** [comment] 2017-05-03 08:53
It's the code I'm using to make some changes. I would like to use it when debugging.

- Fix array.includes errors in Internet Explorer
- Fixed that loader does not disappear when calling remove function.

```
import createElement from 'dom-create-element-query-selector';

export default (...params) => {
    return new IsLoading(params);
};

const formElements = ['form', 'input', 'textarea', 'label', 'fieldset', 'select', 'button'];

const optionsDefault = {
    'type': 'switch',        // switch | replace | full-overlay | overlay
    'text': 'loading',       // Text to display in the loader
    'disableSource': true,   // true | false
    'disableList': []
};

class IsLoading {
    constructor (params) {
        let options = {};
        if (params.length === 0 || (params.length === 1 && !params[0].nodeType)) {
            this._target = null;
            options = {...params[0], type: 'full-overlay'};
        } else {
            this._target = params[0];
            options = params[1];
        }
        this._options = {...optionsDefault, ...options};
        this._fullOverlayId = 'is-loading-full-overlay';
    }

    loading () {
        switch (this._options.type) {
        case 'replace': this._onReplaceType(); break;
        case 'full-overlay': this._onFullOverlayType(); break;
        case 'overlay': this._onElementOverlayType(); break;
        default: this._onSwitchType(); break;
        }
    }

    get targetContent () {
        if (this.isTargetValue) {
            return this._target.value;
        } else {
            return this._target.textContent;
        }
    }

    set targetContent (val) {
        if (this.isTargetValue) {
            this._target.value = val;
        } else {
            this._target.textContent = val;
        }
    }

    get isTargetValue () {
        const node = this._target.nodeName.toLowerCase();
        const type = this._target.attributes.type;

        return (node === 'input' && type && (type.value.toLowerCase() === 'button' || type.value.toLowerCase() === 'submit'));
    }

    restoreContent () {
        const content = this._target.getAttribute('data-is-loading-content');
        if (this.isTargetValue) {
            this._target.value = content;
        } else {
            this._target.textContent = content;
        }
    }

    _onSwitchType () {
        this._toggleElements(false);
        this._target.setAttribute('data-is-loading-content', this.targetContent);
        this.targetContent = this._options.text;
    }

    _onReplaceType () {
        this._toggleElements(false);
        this._target.setAttribute('data-is-loading-content', this.targetContent);
        this._target.innerHTML = '';
        this._target.appendChild(createElement('span.is-loading.is-loading-target', this._options.text));
    }

    _onElementOverlayType () {
        this._toggleElements(false);
        const overlayWrapperClass = '.is-loading-element-overlay';

        if (this._prop('position') === 'static') {
            this._target.setAttribute('data-is-loading-position', 'static');
            this._target.classList.add('is-loading-element-overlay-target');
        }

        if (!this._target.querySelector(overlayWrapperClass)) {
            const overlay = createElement(overlayWrapperClass,
                createElement('.is-loading-text-wrapper', this._options.text)
            );
            overlay.style.borderRadius = this._prop('border-radius');
            this._target.appendChild(overlay);
        }
    }

    _onFullOverlayType () {
        this._toggleElements(false);
        this._showFullOverlay();
    }

    _showFullOverlay () {
        let overlay = document.querySelector(this._fullOverlayId);

        if (!overlay) {
            overlay = createElement(`#${this._fullOverlayId}`,
                createElement('.is-loading-text-wrapper', this._options.text)
            );
            document.querySelector('body').appendChild(overlay);
        }
    }

    _prop (prop) {
        return window.getComputedStyle(this._target).getPropertyValue(prop);
    }

    _toggleElements (status = true) {
        let list = [...this._options.disableList];
        if (this._target && this._options.disableSource === true) {
            list.unshift(this._target);
        }
        list.forEach(item => {
            if (formElements.includes(item.tagName.toLowerCase())) {
                if (status === true) {
                    item.removeAttribute('disabled');
                } else {
                    item.setAttribute('disabled', 'disabled');
                }
            }
            if (status === true) {
                item.classList.remove('disabled');
            } else {
                item.classList.add('disabled');
            }
        });
    }

    remove () {
        this._toggleElements(true);
        if (this._options.type === 'switch') {
            this.restoreContent();
        }
        if (this._target) {
            this._target.removeAttribute('data-is-loading-content');
        }
        if (this._options.type === 'overlay') {
            this._target.removeChild(document.querySelector('.is-loading-element-overlay'));
        }
        if (this._options.type === 'full-overlay') {
            let overlay = document.getElementById(this._fullOverlayId);
            document.querySelector('body').removeChild(overlay);
        }
        if (this._target && this._target.getAttribute('data-is-loading-position')) {
            this._target.removeAttribute('data-is-loading-position');
            this._target.classList.remove('is-loading-element-overlay-target');
        }
    }
}

Array.prototype.includes = function includes(searchElement) {
    // From - https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

    if (this == null) {
        throw new TypeError('Array.prototype.includes called on null or undefined');
    }

    var O = Object(this);
    var len = parseInt(O.length, 10) || 0;
    if (len === 0) {
        return false;
    }
    var n = parseInt(arguments[1], 10) || 0;
    var k;
    if (n >= 0) {
        k = n;
    } else {
        k = len + n;
        if (k < 0) {k = 0;}
    }
    var currentElement;
    while (k < len) {
        currentElement = O[k];
        if (searchElement === currentElement ||
            (searchElement !== searchElement && currentElement !== currentElement)) { // NaN !== NaN
            return true;
        }
        k++;
    }
    return false;
};

```
